"""empty message

Revision ID: 41639054bf10
Revises: 6e69d4292457
Create Date: 2019-01-22 14:22:37.418544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41639054bf10'
down_revision = '6e69d4292457'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('feature',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=120), nullable=True),
    sa.Column('client', sa.String(length=128), nullable=True),
    sa.Column('client_priority', sa.Integer(), nullable=True),
    sa.Column('target_date', sa.DateTime(), nullable=True),
    sa.Column('product_area', sa.String(length=65), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feature_client'), 'feature', ['client'], unique=False)
    op.create_index(op.f('ix_feature_client_priority'), 'feature', ['client_priority'], unique=False)
    op.create_index(op.f('ix_feature_description'), 'feature', ['description'], unique=False)
    op.create_index(op.f('ix_feature_product_area'), 'feature', ['product_area'], unique=False)
    op.create_index(op.f('ix_feature_target_date'), 'feature', ['target_date'], unique=False)
    op.create_index(op.f('ix_feature_title'), 'feature', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feature_title'), table_name='feature')
    op.drop_index(op.f('ix_feature_target_date'), table_name='feature')
    op.drop_index(op.f('ix_feature_product_area'), table_name='feature')
    op.drop_index(op.f('ix_feature_description'), table_name='feature')
    op.drop_index(op.f('ix_feature_client_priority'), table_name='feature')
    op.drop_index(op.f('ix_feature_client'), table_name='feature')
    op.drop_table('feature')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('client')
    # ### end Alembic commands ###
