"""clients table

Revision ID: 8d8cd8d9b2aa
Revises: a47cd75bf176
Create Date: 2019-01-07 13:09:00.322965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d8cd8d9b2aa'
down_revision = 'a47cd75bf176'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('feature', sa.Column('client_id', sa.Integer(), nullable=True))
    op.drop_index('ix_feature_client_priority', table_name='feature')
    op.create_index(op.f('ix_feature_client_priority'), 'feature', ['client_priority'], unique=True)
    op.create_foreign_key(None, 'feature', 'client', ['client_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'feature', type_='foreignkey')
    op.drop_index(op.f('ix_feature_client_priority'), table_name='feature')
    op.create_index('ix_feature_client_priority', 'feature', ['client_priority'], unique=False)
    op.drop_column('feature', 'client_id')
    op.drop_table('client')
    # ### end Alembic commands ###
