"""features table

Revision ID: a47cd75bf176
Revises: 2645c5f56985
Create Date: 2019-01-06 15:15:35.965863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a47cd75bf176'
down_revision = '2645c5f56985'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feature',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=120), nullable=True),
    sa.Column('client', sa.String(length=128), nullable=True),
    sa.Column('client_priority', sa.Integer(), nullable=True),
    sa.Column('target_date', sa.DateTime(), nullable=True),
    sa.Column('product_area', sa.String(length=65), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feature_client'), 'feature', ['client'], unique=False)
    op.create_index(op.f('ix_feature_client_priority'), 'feature', ['client_priority'], unique=False)
    op.create_index(op.f('ix_feature_description'), 'feature', ['description'], unique=False)
    op.create_index(op.f('ix_feature_product_area'), 'feature', ['product_area'], unique=False)
    op.create_index(op.f('ix_feature_target_date'), 'feature', ['target_date'], unique=False)
    op.create_index(op.f('ix_feature_title'), 'feature', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feature_title'), table_name='feature')
    op.drop_index(op.f('ix_feature_target_date'), table_name='feature')
    op.drop_index(op.f('ix_feature_product_area'), table_name='feature')
    op.drop_index(op.f('ix_feature_description'), table_name='feature')
    op.drop_index(op.f('ix_feature_client_priority'), table_name='feature')
    op.drop_index(op.f('ix_feature_client'), table_name='feature')
    op.drop_table('feature')
    # ### end Alembic commands ###
