"""empty message

Revision ID: d5c904663770
Revises: 632420f4b0e6
Create Date: 2019-01-13 17:35:40.896955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5c904663770'
down_revision = '632420f4b0e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feature', sa.Column('client_id', sa.Integer(), nullable=True))
    op.add_column('feature', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'feature', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'feature', 'client', ['client_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'feature', type_='foreignkey')
    op.drop_constraint(None, 'feature', type_='foreignkey')
    op.drop_column('feature', 'user_id')
    op.drop_column('feature', 'client_id')
    # ### end Alembic commands ###
